### ISSUE TITLE
[needed feature] Sync multiple browser tabs 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_prjmapJS#1]
currently we allow sync of 2 divs within one chrome tab. 
We need to allow 2 [or n] tabs in which divs are in sync so projection could be splitted over non-Matrox setup.

**Comment by yasushisakai** [comment]
commit  d3de68743a206c749634d0253435fba245d0e04f
has the sync feature, yet improvements need for exact timing.

**Comment by yasushisakai** [comment]
f667a99

replaced ```htmlvideoNode.load()``` to ```htmlvideoNode.currentPosition=0```

we still observe the loading circles, but the timing (frame #) should be the 
same. This does not solve the communication lag and read-from-memory lag.

tested in Firefox. Is this enough?

**Comment by RELNO** [comment]
Closing until we got projectors to test. Lag might be a non issue.
