### ISSUE TITLE
Synchronisation is sometimes lost when videos reload

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_prjmapJS#10]
If I run the tool on a python web server and I use a long video (longer than 15s), then when the video restarts, the synchronisation goes off completely. Often one side will pause for several seconds while the other continues playing. The following error message appears in the console of the browser where the video did not pause:
"Failed to load resource: net::ERR_CACHE_WRITE_FAILURE"

If I don't use the web server and just open index.html in my browser, then the above issue doesn't apply. However, sometimes, when the video restarts, there will be a small but noticeable (<1s) synchronisation error.

**Comment by RELNO** [comment]
Closing as it seems solved.

**Comment by doorleyr** [comment]
The behaviour is the same as before for me. 

i.e. with the localhost, there are consistently large synchronisation errors. When I open index.html directly in my browser, the videos will generally stay in sync for the first run but after that there will be a small but sometimes noticeable lag.

**Comment by RELNO** [comment]
This require a deeper dive. @yasushisakai  can you give a hand on this?

**Comment by yasushisakai** [comment]
@doorleyr can you provide the mov file? I'll first check if I can reproduce it.

**Comment by yasushisakai** [comment]
# tips for better sync

1. use firefox
2. use direct file access
3. try commit 30c8d0f9edf5addc274cebdef571ca23d6d5d362
