### ISSUE TITLE
Videos not uploading

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_prjmapJS#11]
I tried to load a large file (188.5 MB, 3840 × 2160 resolution, .mov). It can be found under the name '180429_Video_AaltoV04' in CPGMedia/CSS18_Videos_Aaltoi_in_Progress/180429_Video_Aalto

I tried many times to load the video using my own laptop and using the loaner. I also tried with and without the local host. I tried Chrome and Safari. It wasn't able to load on any of these attempts.

The name of the video appears beside the button but the video doesn't appear.

**Comment by RELNO** [comment]
This is most likely a codec/rendering issue. 
I've cloned the `mov` and it didn't work => Than I've exported it using quicktime as 4k and it had no issue. 
I suggest this process for now, as I have no way to debug the actual codec mismatch.  
Closing otherwise.

**Comment by RELNO** [comment]
one more thing: MOV is not a native format for html5 video [see here: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats]. The way to play mov is actually by internally encoding it as mpeg or mp4
