### ISSUE TITLE
Allow 'crop' of media for each individual DIV

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_prjmapJS#4]
in order to crop each projection mapping differently,
we need to allow the media within the `div`to 'shift' the media internally. 

<img width="636" alt="screen shot 2018-04-10 at 20 09 35" src="https://user-images.githubusercontent.com/14296774/38589789-1c02aad8-3cfb-11e8-9690-8695b6b9c6df.png">

**Comment by yasushisakai** [comment]
https://css-tricks.com/clipping-masking-css/

**Comment by RELNO** [comment]
@yasushisakai I think it's more 'shift' than mask that we need. Also, I'm not sure how we do this in a **single** tab case study since the two divs are mirrored

**Comment by RELNO** [comment]
added though Translate in CSS. Closing.
