### ISSUE TITLE
Aspect ratio of Keystone window does not match content

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_prjmapJS#6]
The keystone container is currently a rectangle with a roughly 2:1 aspect ratio. However, both the Aalto and Andorra tables require a roughly square keystone container. This makes accurate Keystoning very difficult. Aalto full table is 3*1.2, therefore half of table is 1.5*1.2. Aspect ratio for Andorra is similar but not exactly the same.

Discussed with @agrignard and @yasushisakai and we're thinking that the best solution for now would be to let the user decide what the aspect ratio will be.

<img width="644" alt="screen shot 2018-04-24 at 15 41 51" src="https://user-images.githubusercontent.com/7722116/39210238-1ac7cf96-47d6-11e8-951f-02d32276b7ec.png">

**Comment by RELNO** [comment]
Not sure what
 > the best solution for now would be to let the user decide what the aspect ratio will be

means. I've added  **content scale control** using `[` and `]`, but not certain that's what you're looking for. In any case, try playing with these CSS values to see if helps: 

<img width="461" alt="screen shot 2018-04-25 at 11 24 47" src="https://user-images.githubusercontent.com/14296774/39255861-7cca5eac-487b-11e8-8efd-2bba4b29305f.png">

**Comment by doorleyr** [comment]
@RELNO by changing the width and height in css and using the '[' and ']' keys I can get the perfect window for the left side of the video but not the right side. For example, if I try to use the '16_KendallDemo9.mov' video:

- The actual width is 714 and height is 720 so I change the width and height to 357 and 720 in the css. 
- I then choose this video
- I press ']' until the left half of the video fits the keystone perfectly

<img width="287" alt="screen shot 2018-04-25 at 12 09 00" src="https://user-images.githubusercontent.com/7722116/39258413-79327586-48a3-11e8-94c4-9a8d8267f2ff.png">

-However, if I try to fit the right half of the video to the window, I can't. If I keep pressing '[', the left edge of the video is not allowed to go outside of the window and so the video just shrinks instead.

<img width="282" alt="screen shot 2018-04-25 at 12 09 16" src="https://user-images.githubusercontent.com/7722116/39258457-82d0973a-48a3-11e8-94e9-7be675a20a01.png">

**Comment by RELNO** [comment]
fixed @https://github.com/CityScope/CS_prjmapJS/commit/8d3f1de0c1ce538d11709ecd3c6fa96b7d2a422c

Went back to %50 divs for keystone, amend your ration based on media
