### ISSUE TITLE
Uploading videos often doesn't work on first attempt

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_prjmapJS#7]
This issue has happened to me several times. I cloned the repository and I was trying to load content contained in the Media folder.

Example workflow:
I select the 'Choose Files' button and select a file, eg. vid1.
The name of the file appears beside the button but no content appears on the screen (see screenshot).
I try again, selecting a different file, vid2. Same result.
I try again, selecting a different file, vid3. This time, the content does appear on the screen.
I select the original file, vid1 and the content does appear on the screen.

Tested using Chrome on Mac.

<img width="1185" alt="screen shot 2018-04-24 at 16 00 19" src="https://user-images.githubusercontent.com/7722116/39211117-aa92f590-47d8-11e8-9e2c-a3fc5d2372d8.png">

**Comment by RELNO** [comment]
Can you try and load more than one video at the time? the code is now set for slideshow [multiple files] and I think you'd either need to load multiple files or load one and click `left` or `right`. anyway, worth fixing.

**Comment by doorleyr** [comment]
I just realised something else. If you choose N videos, then only N-1 of them appear. This is probably why if you choose 1 video, then 0 videos appear.

**Comment by RELNO** [comment]
fixed @ https://github.com/CityScope/CS_prjmapJS/commit/e46b986ba6cad6b4c6185677c22c08c446ffa347
