### ISSUE TITLE
Option to return to undistorted shape

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_prjmapJS#8]
It would be helpful to have a key which will return the keystone window to its undistorted shape. Currently, to achieve this result, you have to clear the cache.

**Comment by RELNO** [comment]
added @https://github.com/CityScope/CS_prjmapJS/commit/fc24d4926d38402fd0ba1154e193136877ad5517

use `ctrl+d` for clearing localstorage and [a must do] refresh
